In [1]:
#Pandas library to create DataFrames
import pandas as pd
#NumPy library for converting data types
import numpy as np

In [56]:
# Files to load
load_states_Amanda = "State_Research_Amanda.csv"
load_states_Ashley = "State_Research_Ashley.csv"
load_states_Erica = "State_Research_Erica.csv"
load_states_Steve = "State_Research_Steve.csv"
load_states_Zack = "State_Research_Zack.csv"

## Amanda States: Idaho, Kansas, Massachusetts, New Mexico, New York, Pennsylvania, Rhode Island, South Dakota, Vermont, Washington

In [6]:
# Read the State_Research_Amanda CSV into a DataFrame
working_state_Amanda = pd.read_csv(load_states_Amanda)
working_state_Amanda.head()

,State,Population,Population Density,Household Size,% Uninsured,% Living in Poverty,% Population 65+,Lockdown Start,Inital Expected\nLockdown End,Phase 1\nRe-Opening Start,Notes,Shipping Laws/Restrictions,Max Shipping Amount,Politcal Alignment Red vs. Blue 2020,Unnamed: 14,Unnamed: 15
0,Idaho,"1,787,065",21.62,2.68,11.0,13.8,16.27,03/25/2020,04/30/2020,NaN,NaN,Wine; requires direct shipper permit,Cannot exceed 24 nine-liter cases of wine annu...,red,NaN,NaN
1,Kansas,"2,913,314",35.63,2.52,9.0,12.4,16.32,03/30/2020,04/19/2020,05/04/2020,"On 05/26/2020 Kansas Govenor ""announced \nthat...",Wine; requires special order shipping license,Cannot exceed 12 standard cases of wine of one...,red,NaN,https://en.wikipedia.org/wiki/COVID-19_pandemi...
2,Massachusetts,"6,892,503",883.65,2.53,2.8,10.8,16.97,03/23/2020,"Extended 03/31/2020, 04/28/2020 and 05/15/2020",05/18/2020,NaN,Wine; requires direct wine shipper license,A direct wine shipper licensee may ship up to ...,blue,NaN,NaN
3,New Mexico,"2,096,829",17.29,2.64,10.7,20.0,18.01,03/13/2020,04/30/2020,05/15/2020,NaN,Wine; requires direct wine shipment permit.\nN...,Not more than two 9-liter cases of wine monthly,blue,NaN,NaN
4,New York,"19,453,561",412.8,2.60,6.5,14.6,16.94,03/22/2020,"04/06/2020, extended to 04/29/2020, then 05/15...",06/08/2020,NaN,Wine; requires out-of-state direct shipper’s l...,No more than 36 cases (no more than nine liter...,blue,NaN,NaN

In [12]:
working_state_Amanda['State'].value_counts()

Idaho            1
Kansas           1
Massachusetts    1
New Mexico       1
New York         1
Pennsylvania     1
Rhode Island     1
South Dakota     1
Vermont          1
Washington       1
Name: State, dtype: int64

In [23]:
working_state_Amanda.dtypes

State                                    object
Population                               object
Population Density                       object
Household Size                          float64
% Uninsured                             float64
% Living in Poverty                     float64
% Population 65+                        float64
Lockdown Start                           object
Inital Expected\nLockdown End            object
Phase 1\nRe-Opening Start                object
Notes                                    object
Shipping Laws/Restrictions               object
Max Shipping Amount                      object
Politcal Alignment Red vs. Blue 2020     object
Unnamed: 14                             float64
Unnamed: 15                              object
dtype: object

## Amanda Cleaning

In [26]:
#Remove "Unnamed:15" and "Unnamed: 14" column from working_state_Amanda.
working_state_Amanda = working_state_Amanda.drop('Unnamed: 15', axis=1)

In [ ]:
working_state_Amanda = working_state_Amanda.drop('Unnamed: 14', axis=1)
working_state_Amanda

In [35]:
#Create df that has "State", "Population", "Lockdown Start", "Initial Expected Lockdown End", "Phase 1 Re-Opening", "Max Shipping Amount", "Politial Alignment Red vs. Blue 2020"
new_amanda_df = working_state_Amanda.filter(["State", "Population", "Lockdown Start", "Inital Expected\nLockdown End", "Phase 1\nRe-Opening Start", "Politcal Alignment Red vs. Blue 2020"])
new_amanda_df

,State,Population,Lockdown Start,Inital Expected\nLockdown End,Phase 1\nRe-Opening Start,Politcal Alignment Red vs. Blue 2020
0,Idaho,"1,787,065",03/25/2020,04/30/2020,NaN,red
1,Kansas,"2,913,314",03/30/2020,04/19/2020,05/04/2020,red
2,Massachusetts,"6,892,503",03/23/2020,"Extended 03/31/2020, 04/28/2020 and 05/15/2020",05/18/2020,blue
3,New Mexico,"2,096,829",03/13/2020,04/30/2020,05/15/2020,blue
4,New York,"19,453,561",03/22/2020,"04/06/2020, extended to 04/29/2020, then 05/15...",06/08/2020,blue
5,Pennsylvania,"12,801,989",03/23/2020,NaN,05/15/2020,blue
6,Rhode Island,"1,059,361",03/28/2020,NaN,05/09/2020,blue
7,South Dakota,"884,659",Never issued a stay-at-home order,NaN,no specific date to re-open as they never closed,red
8,Vermont,"623,989",03/25/2020,NaN,05/15/2020,blue
9,Washington,"7,614,893",03/24/2020,04/03/2020,05/29/2020,blue

In [42]:
new_amanda_df.rename(columns={'Inital Expected\nLockdown End': 'Inital Expected Lockdown End', 
                              'Phase 1\nRe-Opening Start': 'Phase 1 Re-Opening Start', 
                             'Politcal Alignment Red vs. Blue 2020': 'Political Alignment'}, inplace=True)
new_amanda_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment
0,Idaho,"1,787,065",03/25/2020,04/30/2020,NaN,red
1,Kansas,"2,913,314",03/30/2020,04/19/2020,05/04/2020,red
2,Massachusetts,"6,892,503",03/23/2020,"Extended 03/31/2020, 04/28/2020 and 05/15/2020",05/18/2020,blue
3,New Mexico,"2,096,829",03/13/2020,04/30/2020,05/15/2020,blue
4,New York,"19,453,561",03/22/2020,"04/06/2020, extended to 04/29/2020, then 05/15...",06/08/2020,blue
5,Pennsylvania,"12,801,989",03/23/2020,NaN,05/15/2020,blue
6,Rhode Island,"1,059,361",03/28/2020,NaN,05/09/2020,blue
7,South Dakota,"884,659",Never issued a stay-at-home order,NaN,no specific date to re-open as they never closed,red
8,Vermont,"623,989",03/25/2020,NaN,05/15/2020,blue
9,Washington,"7,614,893",03/24/2020,04/03/2020,05/29/2020,blue

In [77]:
#complete_states_df['Inital Expected Lockdown End'] = pd.to_datetime(complete_states_df,'Inital Expected Lockdown End')
new_amanda_df["Inital Expected Lockdown End"] = new_amanda_df["Inital Expected Lockdown End"].dt.strftime('%m/%d/%Y')

KeyError: 'Inital Expected Lockdown End'

In [48]:
#Want to change the Nan to a generic 00/00/0000 date or note somehow that there is no information.
new_amanda_df["Inital Expected Lockdown End"] = new_amanda_df["Inital Expected Lockdown End"].fillna("00/00/000"), inplace=True
new_amanda_df

AttributeError: 'list' object has no attribute 'fillna'

## Ashley States: Alaska, California, Florida, Illinois, Indiana, New Jersey, Noth Dakota, Oklahoma, Oregon, Wyoming

In [16]:
# Read the State_Research_Ashley CSV into a DataFrame
working_state_Ashley = pd.read_csv(load_states_Ashley)
working_state_Ashley.head()

,State,Population,Population Density (people per sq. mile),Household Size,% Uninsured,% Living in Poverty,% Population 65+,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Re-Opening notes,Shipping Laws/Restrictions,Max Shipping Amount,Politcal Alignment Red vs. Blue 2020
0,Alaska,"731,545",1.28,2.81,14.4,10.8,12.52,3/13/2020 * events\n15th* public schools\n23rd...,3/30/20 *but it was extended,April 24th 2020,"Restaurants can open, but owners say doing it ...",Wine shipments prohibited in certain areas,Not more than 5 gallons.,Red
1,California,"39,512,223",253.64,2.96,8.5,14.3,14.78,3/16/20*counties 19th* Statewide,2 wks but continously extended,May 13th,Re-opening based on county level infection rat...,NaN,No Volume Limits,Blue
2,Florida,"21,477,737",400.52,2.65,13.5,14.8,20.94,"4/1/20 *restricts activities to ""essential ser...",30 days,9/25/2020 * all restrictions lifted,NaN,Wine shipments prohibited in certain areas,No Volume Limits – Btl cannot exceed 3L,Red
3,Illinois,"12,671,821",228.24,2.59,7.3,13.1,16.12,"March 17th 2020 *close all schools, 16th close...","March 30, April 30th, indefinitely","May 5th mulit tier reopening, but many busines...",NaN,NaN,12 cases / Individual / Year,Blue
4,Indiana,"6,732,219",187.91,2.53,9.1,14.1,16.13,"March 12 large gatherings limited, March 16th ...",May 1,May 1 multi-stage reopening plan,"Nov 11, 2020 some restrictions re-imposed","Effective July 1, 2015, legislation (SB 113) r...",\nIndividual limit 24 cases/ calendar year \nP...,Red

In [17]:
working_state_Ashley['State'].value_counts()

Alaska         1
California     1
Florida        1
Illinois       1
Indiana        1
New Jersey     1
Noth Dakota    1
Oklahoma       1
Oregon         1
Wyoming        1
Name: State, dtype: int64

In [25]:
working_state_Ashley.dtypes

State                                        object
Population                                   object
Population Density (people per sq. mile)     object
Household Size                              float64
% Uninsured                                 float64
% Living in Poverty                         float64
% Population 65+                            float64
Lockdown Start                               object
Inital Expected Lockdown End                 object
Phase 1 Re-Opening Start                     object
Re-Opening notes                             object
Shipping Laws/Restrictions                   object
Max Shipping Amount                          object
Politcal Alignment Red vs. Blue 2020         object
dtype: object

In [38]:
#Create df that has "State", "Population", "Lockdown Start", "Initial Expected Lockdown End", "Phase 1 Re-Opening", "Max Shipping Amount", "Politial Alignment Red vs. Blue 2020"
new_ashley_df = working_state_Ashley.filter(["State", "Population", "Lockdown Start", "Inital Expected Lockdown End", "Phase 1 Re-Opening Start", "Politcal Alignment Red vs. Blue 2020"])
new_ashley_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Politcal Alignment Red vs. Blue 2020
0,Alaska,"731,545",3/13/2020 * events\n15th* public schools\n23rd...,3/30/20 *but it was extended,April 24th 2020,Red
1,California,"39,512,223",3/16/20*counties 19th* Statewide,2 wks but continously extended,May 13th,Blue
2,Florida,"21,477,737","4/1/20 *restricts activities to ""essential ser...",30 days,9/25/2020 * all restrictions lifted,Red
3,Illinois,"12,671,821","March 17th 2020 *close all schools, 16th close...","March 30, April 30th, indefinitely","May 5th mulit tier reopening, but many busines...",Blue
4,Indiana,"6,732,219","March 12 large gatherings limited, March 16th ...",May 1,May 1 multi-stage reopening plan,Red
5,New Jersey,"8,882,190",March 16th A new executive order immediately c...,unspecified,May 12th,Blue
6,Noth Dakota,"762,062","March 15th schools ordered to close, 19th bars...","March 30, April 20,","April 27-29, schools still remote May 29 large...",Red
7,Oklahoma,"3,956,971",March 24 Gov. Stitt issued “Safer at Home” ord...,unspecified,4/22/2022,Red
8,Oregon,"4,217,737",March 12 schools ordered to close starting Mar...,March 31,May 14th,Blue
9,Wyoming,"578,759","March 20th, 2020 closed schools restaurants ba...",April 3,"May 1st, 2020",Red

In [49]:
new_ashley_df.rename(columns={'Politcal Alignment Red vs. Blue 2020': 'Political Alignment'}, inplace=True)
new_ashley_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment
0,Alaska,"731,545",3/13/2020 * events\n15th* public schools\n23rd...,3/30/20 *but it was extended,April 24th 2020,Red
1,California,"39,512,223",3/16/20*counties 19th* Statewide,2 wks but continously extended,May 13th,Blue
2,Florida,"21,477,737","4/1/20 *restricts activities to ""essential ser...",30 days,9/25/2020 * all restrictions lifted,Red
3,Illinois,"12,671,821","March 17th 2020 *close all schools, 16th close...","March 30, April 30th, indefinitely","May 5th mulit tier reopening, but many busines...",Blue
4,Indiana,"6,732,219","March 12 large gatherings limited, March 16th ...",May 1,May 1 multi-stage reopening plan,Red
5,New Jersey,"8,882,190",March 16th A new executive order immediately c...,unspecified,May 12th,Blue
6,Noth Dakota,"762,062","March 15th schools ordered to close, 19th bars...","March 30, April 20,","April 27-29, schools still remote May 29 large...",Red
7,Oklahoma,"3,956,971",March 24 Gov. Stitt issued “Safer at Home” ord...,unspecified,4/22/2022,Red
8,Oregon,"4,217,737",March 12 schools ordered to close starting Mar...,March 31,May 14th,Blue
9,Wyoming,"578,759","March 20th, 2020 closed schools restaurants ba...",April 3,"May 1st, 2020",Red

## Erica States: Alabama, Colorado, Delaware, Georgia, Iowa, Minnesota, Missouri, Ohio, South Carolina, Virginia

In [18]:
# Read the State_Research_Erica CSV into a DataFrame
working_state_Erica = pd.read_csv(load_states_Erica)
working_state_Erica.head()

,State,Population,Population Density (people per sq. mile),Household Size,% Uninsured,% Living in Poverty,% Population 65+,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Re-Opening notes,Shipping Laws/Restrictions,Max Shipping Amount,Politcal Alignment Red vs. Blue 2020
0,Alabama,"4,903,185",96.81,2.55,10.0,17.5,17.33,"April 4, 2020","April 30, 2020","April 30, 2020",NaN,requires direct wine shipper license,Up to 12 cases of unopened containers of wine ...,Red
1,Colorado,"5,758,736",55.56,2.56,8.1,10.9,14.63,"March 26, 2020","April 26, 2020","April 26, 2020",NaN,requires winery direct shipper’s permit,Unlimited,Blue
2,Delaware,"973,764",499.62,2.58,6.0,11.9,19.40,"March 24, 2020","May 8, 2020","May 31, 2020",NaN,requires a direct shipper license. Direct ship...,The total amount of sparkling wine or still wi...,Blue
3,Georgia,"10,617,423",184.61,2.71,13.7,16.0,14.29,"April 3, 2020","April 30, 2020","April 30, 2020",NaN,requires a special order shipping license,Cannot exceed 12 standard cases of wine of one...,Blue
4,Iowa,"3,155,070",56.48,2.41,4.9,11.7,17.53,NaN,NaN,NaN,Iowa never issued stay at home orders,requires wine direct shipper license,Unlimited,Red

In [19]:
working_state_Erica['State'].value_counts()

Alabama           1
Colorado          1
Delaware          1
Georgia           1
Iowa              1
Minnesota         1
Missouri          1
Ohio              1
South Carolina    1
Virginia          1
Name: State, dtype: int64

In [50]:
working_state_Erica.dtypes

State                                        object
Population                                   object
Population Density (people per sq. mile)    float64
Household Size                              float64
% Uninsured                                 float64
% Living in Poverty                         float64
% Population 65+                            float64
Lockdown Start                               object
Inital Expected Lockdown End                 object
Phase 1 Re-Opening Start                     object
Re-Opening notes                             object
Shipping Laws/Restrictions                   object
Max Shipping Amount                          object
Politcal Alignment Red vs. Blue 2020         object
dtype: object

In [51]:
#Create df that has "State", "Population", "Lockdown Start", "Initial Expected Lockdown End", "Phase 1 Re-Opening", "Max Shipping Amount", "Politial Alignment Red vs. Blue 2020"
new_erica_df = working_state_Erica.filter(["State", "Population", "Lockdown Start", "Inital Expected Lockdown End", "Phase 1 Re-Opening Start", "Politcal Alignment Red vs. Blue 2020"])
new_erica_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Politcal Alignment Red vs. Blue 2020
0,Alabama,"4,903,185","April 4, 2020","April 30, 2020","April 30, 2020",Red
1,Colorado,"5,758,736","March 26, 2020","April 26, 2020","April 26, 2020",Blue
2,Delaware,"973,764","March 24, 2020","May 8, 2020","May 31, 2020",Blue
3,Georgia,"10,617,423","April 3, 2020","April 30, 2020","April 30, 2020",Blue
4,Iowa,"3,155,070",NaN,NaN,NaN,Red
5,Minnesota,"5,639,632","March 27, 2020","May 4, 2020","May 17, 2020",Blue
6,Missouri,"6,137,428","April 6, 2020","May 3, 2020","May 3, 2020",Red
7,Ohio,"11,689,100","March 23, 2020","May 19, 2020","May 19, 2020",Red
8,South Carolina,"5,148,714","April 7, 2020","May 4, 2020","May 4, 2020",Red
9,Virginia,"8,535,519","March 30, 2020","May 15, 2020","May 29, 2020",Blue

In [52]:
new_erica_df.rename(columns={'Politcal Alignment Red vs. Blue 2020': 'Political Alignment'}, inplace=True)
new_erica_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment
0,Alabama,"4,903,185","April 4, 2020","April 30, 2020","April 30, 2020",Red
1,Colorado,"5,758,736","March 26, 2020","April 26, 2020","April 26, 2020",Blue
2,Delaware,"973,764","March 24, 2020","May 8, 2020","May 31, 2020",Blue
3,Georgia,"10,617,423","April 3, 2020","April 30, 2020","April 30, 2020",Blue
4,Iowa,"3,155,070",NaN,NaN,NaN,Red
5,Minnesota,"5,639,632","March 27, 2020","May 4, 2020","May 17, 2020",Blue
6,Missouri,"6,137,428","April 6, 2020","May 3, 2020","May 3, 2020",Red
7,Ohio,"11,689,100","March 23, 2020","May 19, 2020","May 19, 2020",Red
8,South Carolina,"5,148,714","April 7, 2020","May 4, 2020","May 4, 2020",Red
9,Virginia,"8,535,519","March 30, 2020","May 15, 2020","May 29, 2020",Blue

## Steve States: Arizona, Arkansas, Conneticut, Kentucky, Louisiana, Montana, Nebraska, Nevada, West Virginia, Wisconsin

In [20]:
# Read the State_Research_Steve CSV into a DataFrame
working_state_Steve = pd.read_csv(load_states_Steve)
working_state_Steve.head()

,State,Population,Population Density (people per sq. mile),Household Size,% Uninsured,% Living in Poverty,% Population 65+,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Re-Opening notes,Shipping Laws/Restrictions,Max Shipping Amount,Politcal Alignment Red vs. Blue 2020
0,Arizona,"7,278,717",64.08,2.69,10.9,16.1,17.98,"April 30, 2020","May 15, 2020","May 18, 2020","Slowly started reopening by ""essential"" defini...",DTC permit required.,12 nine-liter cases of wine.,Blue
1,Arkansas,"3,017,804",58.00,2.52,9.0,17.6,17.36,"March 15, 2020","March 27, 2020","June 5,2020",NaN,Consumer must be present at purchase unless sh...,One case of vinous liquor per consumer in any ...,Red
2,Conneticut,"3,565,287",736.33,2.54,5.6,10.0,17.68,"May 15th, 2020",NaN,NaN,NaN,NaN,2 cases per person every 2 months,Blue
3,Kentucky,"4,467,673",113.15,1.49,6.1,17.9,16.80,NaN,NaN,NaN,NaN,"Effective March 12, 2021, brand registration i...",\n10 cases per person per month,Red
4,Louisiana,"4,648,794",107.60,2.61,10.7,19.4,15.94,NaN,NaN,NaN,NaN,Product Restrictions\n1. ONLY wine packaged in...,12 cases per person per year,Red

In [21]:
working_state_Steve['State'].value_counts()

Arizona          1
Arkansas         1
Conneticut       1
Kentucky         1
Louisiana        1
Montana          1
Nebraska         1
Nevada           1
West Virginia    1
Wisconsin        1
Name: State, dtype: int64

In [53]:
working_state_Steve.dtypes

State                                        object
Population                                   object
Population Density (people per sq. mile)    float64
Household Size                              float64
% Uninsured                                 float64
% Living in Poverty                         float64
% Population 65+                            float64
Lockdown Start                               object
Inital Expected Lockdown End                 object
Phase 1 Re-Opening Start                     object
Re-Opening notes                             object
Shipping Laws/Restrictions                   object
Max Shipping Amount                          object
Politcal Alignment Red vs. Blue 2020         object
dtype: object

In [54]:
#Create df that has "State", "Population", "Lockdown Start", "Initial Expected Lockdown End", "Phase 1 Re-Opening", "Max Shipping Amount", "Politial Alignment Red vs. Blue 2020"
new_steve_df = working_state_Steve.filter(["State", "Population", "Lockdown Start", "Inital Expected Lockdown End", "Phase 1 Re-Opening Start", "Politcal Alignment Red vs. Blue 2020"])
new_steve_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Politcal Alignment Red vs. Blue 2020
0,Arizona,"7,278,717","April 30, 2020","May 15, 2020","May 18, 2020",Blue
1,Arkansas,"3,017,804","March 15, 2020","March 27, 2020","June 5,2020",Red
2,Conneticut,"3,565,287","May 15th, 2020",NaN,NaN,Blue
3,Kentucky,"4,467,673",NaN,NaN,NaN,Red
4,Louisiana,"4,648,794",NaN,NaN,NaN,Red
5,Montana,"1,068,778",NaN,NaN,NaN,Red
6,Nebraska,"1,934,408",NaN,NaN,NaN,Red
7,Nevada,"3,080,156",NaN,NaN,NaN,Blue
8,West Virginia,"1,792,147",NaN,NaN,NaN,Red
9,Wisconsin,"5,822,434",NaN,NaN,NaN,Blue

In [55]:
new_steve_df.rename(columns={'Politcal Alignment Red vs. Blue 2020': 'Political Alignment'}, inplace=True)
new_steve_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment
0,Arizona,"7,278,717","April 30, 2020","May 15, 2020","May 18, 2020",Blue
1,Arkansas,"3,017,804","March 15, 2020","March 27, 2020","June 5,2020",Red
2,Conneticut,"3,565,287","May 15th, 2020",NaN,NaN,Blue
3,Kentucky,"4,467,673",NaN,NaN,NaN,Red
4,Louisiana,"4,648,794",NaN,NaN,NaN,Red
5,Montana,"1,068,778",NaN,NaN,NaN,Red
6,Nebraska,"1,934,408",NaN,NaN,NaN,Red
7,Nevada,"3,080,156",NaN,NaN,NaN,Blue
8,West Virginia,"1,792,147",NaN,NaN,NaN,Red
9,Wisconsin,"5,822,434",NaN,NaN,NaN,Blue

## Zack States: Hawaii, Maine, Maryland, Michigan, Mississippi, New Hampshire, North Carolina, Tennessee, Texas, Utah

In [57]:
#Read the State_Research_Zack CSV into a DataFrame
working_state_Zack = pd.read_csv(load_states_Zack)
working_state_Zack.head()

,State,Population,Population Density (people per sq. mile),Household Size,% Uninsured,% Living in Poverty,% Population 65+,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Re-Opening notes,Shipping Laws/Restrictions,Max Shipping Amount,Politcal Alignment Red vs. Blue 2020
0,Hawaii,"1,415,872",220.44,3.02,4.1,9.9,18.96,Mar 23 2020,NaN,"May. 5, 2020",NaN,NaN,6 cases per household address per winery,Blue
1,Maine,"1,344,212",43.58,2.33,8.3,12.5,21.22,"Mar 18, 2020",NaN,"May. 1, 2020",NaN,“Wine coolers” may NOT be shipped DTC \...,12 cases per recipient address,Blue
2,Maryland,"6,045,680",622.82,2.67,6.5,9.4,15.87,"Mar 12, 2020","Mar 27, 2020","May 13, 2020",NaN,NaN,18 cases per address,Blue
3,Michigan,"9,986,857",176.64,2.49,6.1,15.0,17.68,"Mar 12, 2020",NaN,"June 1, 2020",NaN,NaN,"1,500 cases per year",Blue
4,Mississippi,"2,976,149",63.43,2.62,12.7,20.8,16.35,"Apr 3, 2020","April 20, 2020","April 27, 2020",NaN,DTC shipping prohibited,DTC shipping prohibited,Red

In [58]:
working_state_Zack['State'].value_counts()

Hawaii            1
Maine             1
Maryland          1
Michigan          1
Mississippi       1
New Hampshire     1
North Carolina    1
Tennessee         1
Texas             1
Utah              1
Name: State, dtype: int64

In [59]:
working_state_Zack.dtypes

State                                        object
Population                                   object
Population Density (people per sq. mile)    float64
Household Size                              float64
% Uninsured                                 float64
% Living in Poverty                         float64
% Population 65+                            float64
Lockdown Start                               object
Inital Expected Lockdown End                 object
Phase 1 Re-Opening Start                     object
Re-Opening notes                             object
Shipping Laws/Restrictions                   object
Max Shipping Amount                          object
Politcal Alignment Red vs. Blue 2020         object
dtype: object

In [61]:
#Create df that has "State", "Population", "Lockdown Start", "Initial Expected Lockdown End", "Phase 1 Re-Opening", "Max Shipping Amount", "Politial Alignment Red vs. Blue 2020"
new_zack_df = working_state_Zack.filter(["State", "Population", "Lockdown Start", "Inital Expected Lockdown End", "Phase 1 Re-Opening Start", "Politcal Alignment Red vs. Blue 2020"])
new_zack_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Politcal Alignment Red vs. Blue 2020
0,Hawaii,"1,415,872",Mar 23 2020,NaN,"May. 5, 2020",Blue
1,Maine,"1,344,212","Mar 18, 2020",NaN,"May. 1, 2020",Blue
2,Maryland,"6,045,680","Mar 12, 2020","Mar 27, 2020","May 13, 2020",Blue
3,Michigan,"9,986,857","Mar 12, 2020",NaN,"June 1, 2020",Blue
4,Mississippi,"2,976,149","Apr 3, 2020","April 20, 2020","April 27, 2020",Red
5,New Hampshire,"1,359,711","Mar 26, 2020",NaN,"May 18, 2020",Blue
6,North Carolina,"10,488,084","Mar 30, 2020",NaN,"May 20, 2020",Red
7,Tennessee,"6,829,174","Apr 2, 2020","Apr 14, 2020","May 1, 2020",Red
8,Texas,"28,995,881","Mar 31, 2020","May 4, 2020","May 1, 2020",Red
9,Utah,"3,205,958","Mar 27, 2020",NaN,"May 1, 2020",Red

In [62]:
new_zack_df.rename(columns={'Politcal Alignment Red vs. Blue 2020': 'Political Alignment'}, inplace=True)
new_zack_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment
0,Hawaii,"1,415,872",Mar 23 2020,NaN,"May. 5, 2020",Blue
1,Maine,"1,344,212","Mar 18, 2020",NaN,"May. 1, 2020",Blue
2,Maryland,"6,045,680","Mar 12, 2020","Mar 27, 2020","May 13, 2020",Blue
3,Michigan,"9,986,857","Mar 12, 2020",NaN,"June 1, 2020",Blue
4,Mississippi,"2,976,149","Apr 3, 2020","April 20, 2020","April 27, 2020",Red
5,New Hampshire,"1,359,711","Mar 26, 2020",NaN,"May 18, 2020",Blue
6,North Carolina,"10,488,084","Mar 30, 2020",NaN,"May 20, 2020",Red
7,Tennessee,"6,829,174","Apr 2, 2020","Apr 14, 2020","May 1, 2020",Red
8,Texas,"28,995,881","Mar 31, 2020","May 4, 2020","May 1, 2020",Red
9,Utah,"3,205,958","Mar 27, 2020",NaN,"May 1, 2020",Red

# Append all five df into one overall states df:

In [63]:
#Append all five df into one overall states df:
complete_states_df = new_amanda_df.append([new_ashley_df,
                                           new_erica_df,
                                           new_steve_df,
                                           new_zack_df], ignore_index = True)
complete_states_df.head()

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment,Inital Expected Lockdown End,Phase 1 Re-Opening Start
0,Idaho,"1,787,065",03/25/2020,04/30/2020,NaN,red,NaN,NaN
1,Kansas,"2,913,314",03/30/2020,04/19/2020,05/04/2020,red,NaN,NaN
2,Massachusetts,"6,892,503",03/23/2020,"Extended 03/31/2020, 04/28/2020 and 05/15/2020",05/18/2020,blue,NaN,NaN
3,New Mexico,"2,096,829",03/13/2020,04/30/2020,05/15/2020,blue,NaN,NaN
4,New York,"19,453,561",03/22/2020,"04/06/2020, extended to 04/29/2020, then 05/15...",06/08/2020,blue,NaN,NaN

In [69]:
#Order states alphabetically
compelte_states_df = complete_states_df.sort_values(by=["State"], inplace=True, ascending=True)
complete_states_df

,State,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment,Inital Expected Lockdown End,Phase 1 Re-Opening Start
20,Alabama,"4,903,185","April 4, 2020",NaN,NaN,Red,"April 30, 2020","April 30, 2020"
10,Alaska,"731,545",3/13/2020 * events\n15th* public schools\n23rd...,NaN,NaN,Red,3/30/20 *but it was extended,April 24th 2020
30,Arizona,"7,278,717","April 30, 2020",NaN,NaN,Blue,"May 15, 2020","May 18, 2020"
31,Arkansas,"3,017,804","March 15, 2020",NaN,NaN,Red,"March 27, 2020","June 5,2020"
11,California,"39,512,223",3/16/20*counties 19th* Statewide,NaN,NaN,Blue,2 wks but continously extended,May 13th
21,Colorado,"5,758,736","March 26, 2020",NaN,NaN,Blue,"April 26, 2020","April 26, 2020"
32,Conneticut,"3,565,287","May 15th, 2020",NaN,NaN,Blue,NaN,NaN
22,Delaware,"973,764","March 24, 2020",NaN,NaN,Blue,"May 8, 2020","May 31, 2020"
12,Florida,"21,477,737","4/1/20 *restricts activities to ""essential ser...",NaN,NaN,Red,30 days,9/25/2020 * all restrictions lifted
23,Georgia,"10,617,423","April 3, 2020",NaN,NaN,Blue,"April 30, 2020","April 30, 2020"
40,Hawaii,"1,415,872",Mar 23 2020,NaN,NaN,Blue,NaN,"May. 5, 2020"
0,Idaho,"1,787,065",03/25/2020,04/30/2020,NaN,red,NaN,NaN
13,Illinois,"12,671,821","March 17th 2020 *close all schools, 16th close...",NaN,NaN,Blue,"March 30, April 30th, indefinitely","May 5th mulit tier reopening, but many busines..."
14,Indiana,"6,732,219","March 12 large gatherings limited, March 16th ...",NaN,NaN,Red,May 1,May 1 multi-stage reopening plan
24,Iowa,"3,155,070",NaN,NaN,NaN,Red,NaN,NaN
1,Kansas,"2,913,314",03/30/2020,04/19/2020,05/04/2020,red,NaN,NaN
33,Kentucky,"4,467,673",NaN,NaN,NaN,Red,NaN,NaN
34,Louisiana,"4,648,794",NaN,NaN,NaN,Red,NaN,NaN
41,Maine,"1,344,212","Mar 18, 2020",NaN,NaN,Blue,NaN,"May. 1, 2020"
42,Maryland,"6,045,680","Mar 12, 2020",NaN,NaN,Blue,"Mar 27, 2020","May 13, 2020"
2,Massachusetts,"6,892,503",03/23/2020,"Extended 03/31/2020, 04/28/2020 and 05/15/2020",05/18/2020,blue,NaN,NaN
43,Michigan,"9,986,857","Mar 12, 2020",NaN,NaN,Blue,NaN,"June 1, 2020"
25,Minnesota,"5,639,632","March 27, 2020",NaN,NaN,Blue,"May 4, 2020","May 17, 2020"
44,Mississippi,"2,976,149","Apr 3, 2020",NaN,NaN,Red,"April 20, 2020","April 27, 2020"
26,Missouri,"6,137,428","April 6, 2020",NaN,NaN,Red,"May 3, 2020","May 3, 2020"
35,Montana,"1,068,778",NaN,NaN,NaN,Red,NaN,NaN
36,Nebraska,"1,934,408",NaN,NaN,NaN,Red,NaN,NaN
37,Nevada,"3,080,156",NaN,NaN,NaN,Blue,NaN,NaN
45,New Hampshire,"1,359,711","Mar 26, 2020",NaN,NaN,Blue,NaN,"May 18, 2020"
15,New Jersey,"8,882,190",March 16th A new executive order immediately c...,NaN,NaN,Blue,unspecified,May 12th
3,New Mexico,"2,096,829",03/13/2020,04/30/2020,05/15/2020,blue,NaN,NaN
4,New York,"19,453,561",03/22/2020,"04/06/2020, extended to 04/29/2020, then 05/15...",06/08/2020,blue,NaN,NaN
46,North Carolina,"10,488,084","Mar 30, 2020",NaN,NaN,Red,NaN,"May 20, 2020"
16,Noth Dakota,"762,062","March 15th schools ordered to close, 19th bars...",NaN,NaN,Red,"March 30, April 20,","April 27-29, schools still remote May 29 large..."
27,Ohio,"11,689,100","March 23, 2020",NaN,NaN,Red,"May 19, 2020","May 19, 2020"
17,Oklahoma,"3,956,971",March 24 Gov. Stitt issued “Safer at Home” ord...,NaN,NaN,Red,unspecified,4/22/2022
18,Oregon,"4,217,737",March 12 schools ordered to close starting Mar...,NaN,NaN,Blue,March 31,May 14th
5,Pennsylvania,"12,801,989",03/23/2020,NaN,05/15/2020,blue,NaN,NaN
6,Rhode Island,"1,059,361",03/28/2020,NaN,05/09/2020,blue,NaN,NaN
28,South Carolina,"5,148,714","April 7, 2020",NaN,NaN,Red,"May 4, 2020","May 4, 2020"
7,South Dakota,"884,659",Never issued a stay-at-home order,NaN,no specific date to re-open as they never closed,red,NaN,NaN
47,Tennessee,"6,829,174","Apr 2, 2020",NaN,NaN,Red,"Apr 14, 2020","May 1, 2020"
48,Texas,"28,995,881","Mar 31, 2020",NaN,NaN,Red,"May 4, 2020","May 1, 2020"
49,Utah,"3,205,958","Mar 27, 2020",NaN,NaN,Red,NaN,"May 1, 2020"
8,Vermont,"623,989",03/25/2020,NaN,05/15/2020,blue,NaN,NaN
29,Virginia,"8,535,519","March 30, 2020",NaN,NaN,Blue,"May 15, 2020","May 29, 2020"
9,Washington,"7,614,893",03/24/2020,04/03/2020,05/29/2020,blue,NaN,NaN
38,West Virginia,"1,792,147",NaN,NaN,NaN,Red,NaN,NaN
39,Wisconsin,"5,822,434",NaN,NaN,NaN,Blue,NaN,NaN
19,Wyoming,"578,759","March 20th, 2020 closed schools restaurants ba...",NaN,NaN,Red,April 3,"May 1st, 2020"

In [70]:
complete_states_df = complete_states_df.set_index("State")
complete_states_df

,Population,Lockdown Start,Inital Expected Lockdown End,Phase 1 Re-Opening Start,Political Alignment,Inital Expected Lockdown End,Phase 1 Re-Opening Start
State,,,,,,,
Alabama,"4,903,185","April 4, 2020",NaN,NaN,Red,"April 30, 2020","April 30, 2020"
Alaska,"731,545",3/13/2020 * events\n15th* public schools\n23rd...,NaN,NaN,Red,3/30/20 *but it was extended,April 24th 2020
Arizona,"7,278,717","April 30, 2020",NaN,NaN,Blue,"May 15, 2020","May 18, 2020"
Arkansas,"3,017,804","March 15, 2020",NaN,NaN,Red,"March 27, 2020","June 5,2020"
California,"39,512,223",3/16/20*counties 19th* Statewide,NaN,NaN,Blue,2 wks but continously extended,May 13th
Colorado,"5,758,736","March 26, 2020",NaN,NaN,Blue,"April 26, 2020","April 26, 2020"
Conneticut,"3,565,287","May 15th, 2020",NaN,NaN,Blue,NaN,NaN
Delaware,"973,764","March 24, 2020",NaN,NaN,Blue,"May 8, 2020","May 31, 2020"
Florida,"21,477,737","4/1/20 *restricts activities to ""essential ser...",NaN,NaN,Red,30 days,9/25/2020 * all restrictions lifted
Georgia,"10,617,423","April 3, 2020",NaN,NaN,Blue,"April 30, 2020","April 30, 2020"
Hawaii,"1,415,872",Mar 23 2020,NaN,NaN,Blue,NaN,"May. 5, 2020"
Idaho,"1,787,065",03/25/2020,04/30/2020,NaN,red,NaN,NaN
Illinois,"12,671,821","March 17th 2020 *close all schools, 16th close...",NaN,NaN,Blue,"March 30, April 30th, indefinitely","May 5th mulit tier reopening, but many busines..."
Indiana,"6,732,219","March 12 large gatherings limited, March 16th ...",NaN,NaN,Red,May 1,May 1 multi-stage reopening plan
Iowa,"3,155,070",NaN,NaN,NaN,Red,NaN,NaN
Kansas,"2,913,314",03/30/2020,04/19/2020,05/04/2020,red,NaN,NaN
Kentucky,"4,467,673",NaN,NaN,NaN,Red,NaN,NaN
Louisiana,"4,648,794",NaN,NaN,NaN,Red,NaN,NaN
Maine,"1,344,212","Mar 18, 2020",NaN,NaN,Blue,NaN,"May. 1, 2020"
Maryland,"6,045,680","Mar 12, 2020",NaN,NaN,Blue,"Mar 27, 2020","May 13, 2020"
Massachusetts,"6,892,503",03/23/2020,"Extended 03/31/2020, 04/28/2020 and 05/15/2020",05/18/2020,blue,NaN,NaN
Michigan,"9,986,857","Mar 12, 2020",NaN,NaN,Blue,NaN,"June 1, 2020"
Minnesota,"5,639,632","March 27, 2020",NaN,NaN,Blue,"May 4, 2020","May 17, 2020"
Mississippi,"2,976,149","Apr 3, 2020",NaN,NaN,Red,"April 20, 2020","April 27, 2020"
Missouri,"6,137,428","April 6, 2020",NaN,NaN,Red,"May 3, 2020","May 3, 2020"
Montana,"1,068,778",NaN,NaN,NaN,Red,NaN,NaN
Nebraska,"1,934,408",NaN,NaN,NaN,Red,NaN,NaN
Nevada,"3,080,156",NaN,NaN,NaN,Blue,NaN,NaN
New Hampshire,"1,359,711","Mar 26, 2020",NaN,NaN,Blue,NaN,"May 18, 2020"
New Jersey,"8,882,190",March 16th A new executive order immediately c...,NaN,NaN,Blue,unspecified,May 12th
New Mexico,"2,096,829",03/13/2020,04/30/2020,05/15/2020,blue,NaN,NaN
New York,"19,453,561",03/22/2020,"04/06/2020, extended to 04/29/2020, then 05/15...",06/08/2020,blue,NaN,NaN
North Carolina,"10,488,084","Mar 30, 2020",NaN,NaN,Red,NaN,"May 20, 2020"
Noth Dakota,"762,062","March 15th schools ordered to close, 19th bars...",NaN,NaN,Red,"March 30, April 20,","April 27-29, schools still remote May 29 large..."
Ohio,"11,689,100","March 23, 2020",NaN,NaN,Red,"May 19, 2020","May 19, 2020"
Oklahoma,"3,956,971",March 24 Gov. Stitt issued “Safer at Home” ord...,NaN,NaN,Red,unspecified,4/22/2022
Oregon,"4,217,737",March 12 schools ordered to close starting Mar...,NaN,NaN,Blue,March 31,May 14th
Pennsylvania,"12,801,989",03/23/2020,NaN,05/15/2020,blue,NaN,NaN
Rhode Island,"1,059,361",03/28/2020,NaN,05/09/2020,blue,NaN,NaN
South Carolina,"5,148,714","April 7, 2020",NaN,NaN,Red,"May 4, 2020","May 4, 2020"
South Dakota,"884,659",Never issued a stay-at-home order,NaN,no specific date to re-open as they never closed,red,NaN,NaN
Tennessee,"6,829,174","Apr 2, 2020",NaN,NaN,Red,"Apr 14, 2020","May 1, 2020"
Texas,"28,995,881","Mar 31, 2020",NaN,NaN,Red,"May 4, 2020","May 1, 2020"
Utah,"3,205,958","Mar 27, 2020",NaN,NaN,Red,NaN,"May 1, 2020"
Vermont,"623,989",03/25/2020,NaN,05/15/2020,blue,NaN,NaN
Virginia,"8,535,519","March 30, 2020",NaN,NaN,Blue,"May 15, 2020","May 29, 2020"
Washington,"7,614,893",03/24/2020,04/03/2020,05/29/2020,blue,NaN,NaN
West Virginia,"1,792,147",NaN,NaN,NaN,Red,NaN,NaN
Wisconsin,"5,822,434",NaN,NaN,NaN,Blue,NaN,NaN
Wyoming,"578,759","March 20th, 2020 closed schools restaurants ba...",NaN,NaN,Red,April 3,"May 1st, 2020"

In [75]:
#NEED TO FIX DATES DTYPES SO ALL THE NAN's ARE CORRECTED.
#complete_states_df['Inital Expected Lockdown End'] = pd.to_datetime(complete_states_df,'Inital Expected Lockdown End')
complete_states_df["Inital Expected Lockdown End"] = complete_states_df["Inital Expected Lockdown End"].dt.strftime('%m/%d/%Y')

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
#Export complete_states_df to .csv
#complete_states_df.to_csv('Complete_states.csv')